/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthResetLinkImport } from './routes/auth/ResetLink'
import { Route as AuthLoginImport } from './routes/auth/Login'
import { Route as AuthForgotPasswordImport } from './routes/auth/ForgotPassword'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetLinkRoute = AuthResetLinkImport.update({
  id: '/auth/ResetLink',
  path: '/auth/ResetLink',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/Login',
  path: '/auth/Login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/ForgotPassword',
  path: '/auth/ForgotPassword',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/ForgotPassword': {
      id: '/auth/ForgotPassword'
      path: '/auth/ForgotPassword'
      fullPath: '/auth/ForgotPassword'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/Login': {
      id: '/auth/Login'
      path: '/auth/Login'
      fullPath: '/auth/Login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/ResetLink': {
      id: '/auth/ResetLink'
      path: '/auth/ResetLink'
      fullPath: '/auth/ResetLink'
      preLoaderRoute: typeof AuthResetLinkImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordRoute
  '/auth/Login': typeof AuthLoginRoute
  '/auth/ResetLink': typeof AuthResetLinkRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordRoute
  '/auth/Login': typeof AuthLoginRoute
  '/auth/ResetLink': typeof AuthResetLinkRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordRoute
  '/auth/Login': typeof AuthLoginRoute
  '/auth/ResetLink': typeof AuthResetLinkRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/ForgotPassword' | '/auth/Login' | '/auth/ResetLink'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/ForgotPassword' | '/auth/Login' | '/auth/ResetLink'
  id:
    | '__root__'
    | '/'
    | '/auth/ForgotPassword'
    | '/auth/Login'
    | '/auth/ResetLink'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetLinkRoute: typeof AuthResetLinkRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetLinkRoute: AuthResetLinkRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/ForgotPassword",
        "/auth/Login",
        "/auth/ResetLink"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/ForgotPassword": {
      "filePath": "auth/ForgotPassword.tsx"
    },
    "/auth/Login": {
      "filePath": "auth/Login.tsx"
    },
    "/auth/ResetLink": {
      "filePath": "auth/ResetLink.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
